//
//  HomeModels.swift
//  TheArabianCenter
//
//  Created by Ahmed Henawey on 2/18/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import RxSwift

struct Home
{
    struct Offer
    {
        struct Image {
            struct Request {
                var event: Event<[String : AnyObject]>
            }
            struct Response {
                var result:[String:AnyObject]
            }
            struct ViewModel {
                var image:UIImage
            }
            
            enum Error:Swift.Error {
                case noImageFound
                case configurationMissing
                case failure(error:Swift.Error)
                
                var localizedDescription: String{
                    switch self {
                    case .noImageFound:
                        return NSLocalizedString("noImageFound", comment: "")
                        
                    case .configurationMissing:
                        return NSLocalizedString("configurationMissing", comment: "")
                    case let .failure(error):
                        return error.localizedDescription
                    }
                }
            }
        }
    }
}
