//
//  HomeInteractor.swift
//  TheArabianCenter
//
//  Created by Ahmed Henawey on 2/18/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol HomeInteractorInput
{
  func doSomething(request: Home.Something.Request)
}

protocol HomeInteractorOutput
{
  func presentSomething(response: Home.Something.Response)
}

class HomeInteractor: HomeInteractorInput
{
  var output: HomeInteractorOutput!
  var worker: HomeWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: Home.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = HomeWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = Home.Something.Response()
    output.presentSomething(response: response)
  }
}
