//
//  HomeRouter.swift
//  TheArabianCenter
//
//  Created by Ahmed Henawey on 2/18/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import RxSwift

protocol HomeRouterInput
{
    func navigateToSharer()
}

class HomeRouter: HomeRouterInput
{
    weak var viewController: HomeViewController!
    
    // MARK: - Navigation
    
    
    /// Navigate to Sharer View Controller through Segue
    func navigateToSharer()
    {
        // Trigger a storyboard segue
        viewController.performSegue(withIdentifier: "showSharer", sender: viewController)
        
    }
    
    // MARK: - Communication
    
    /// Teach the router which scenes it can communicate with
    ///
    /// - Parameter segue: Segue request the data 
    func passDataToNextScene(segue: UIStoryboardSegue)
    {
        if segue.identifier == "showSharer" {
            passDataToSharerScene(segue: segue)
        }
    }
    
    /// Teach the router how to pass data to the next scene
    ///
    /// - Parameter segue: Segue request the data
    func passDataToSharerScene(segue: UIStoryboardSegue)
    {
        let shareViewController = segue.destination as! ShareViewController
        shareViewController.output.image = Variable(viewController.output.image)
        shareViewController.output.userLocation = viewController.output.userLocation
    }
}
