//
//  HomeConfigurator.swift
//  TheArabianCenter
//
//  Created by Ahmed Henawey on 2/18/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension HomeViewController: HomePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension HomeInteractor: HomeViewControllerOutput
{
}

extension HomePresenter: HomeInteractorOutput
{
}

class HomeConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = HomeConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: HomeViewController)
  {
    let router = HomeRouter()
    router.viewController = viewController
    
    let presenter = HomePresenter()
    presenter.output = viewController
    
    let interactor = HomeInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
