//
//  QRScannerRouter.swift
//  TGTG
//
//  Created by Ahmed Henawey on 1/25/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol QRScannerRouterInput
{
    func close()
}

class QRScannerRouter: QRScannerRouterInput
{
    weak var viewController: QRScannerViewController!
    
    // MARK: - Navigation
    
    func close()
    {
        // NOTE: Teach the router how to navigate to another scene. Some examples follow:
        
        guard let navigationController = viewController.navigationController else{
            
            let output = self.viewController.presentingViewController as? HomeViewController
            output?.output.qrValue = viewController.output.qrValue
            
            self.viewController.dismiss(animated: true, completion: nil)
            
            
            return
        }
        
        //pass data through navigation view controller
        if let index = navigationController.viewControllers.index(of: viewController){
            let output = navigationController.viewControllers[index - 1] as? HomeViewController
            output?.output.qrValue = viewController.output.qrValue
        }
        
        
        navigationController.popViewController(animated: true)
    }
    
    // MARK: - Communication
    
    func passDataToNextScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router which scenes it can communicate with
        
//        if segue.identifier == "ShowSomewhereScene" {
//            passDataToSomewhereScene(segue: segue)
//        }
    }
    
    func passDataToSomewhereScene(segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router how to pass data to the next scene
        
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
