//
//  QRScannerModels.swift
//  TGTG
//
//  Created by Ahmed Henawey on 1/25/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct QRScanner
{
    struct Prepare
    {
        struct Request
        {
            var view:UIView
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    struct Scan
    {
        struct Request
        {
            
        }
        struct Response
        {
            var value:String
        }
        struct ViewModel
        {
            var value:String
        }
    }
    
    enum Error : Swift.Error {
        case unableToPrepareScanner
    }
}
