//
//  QRScannerConfigurator.swift
//  TGTG
//
//  Created by Ahmed Henawey on 1/25/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension QRScannerViewController: QRScannerPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension QRScannerInteractor: QRScannerViewControllerOutput
{
}

extension QRScannerPresenter: QRScannerInteractorOutput
{
}

class QRScannerConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = QRScannerConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: QRScannerViewController)
  {
    let router = QRScannerRouter()
    router.viewController = viewController
    
    let presenter = QRScannerPresenter()
    presenter.output = viewController
    
    let interactor = QRScannerInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
