//
//  ShareConfigurator.swift
//  TheArabianCenter
//
//  Created by Ahmed Henawey on 2/23/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ShareViewController: SharePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ShareInteractor: ShareViewControllerOutput
{
}

extension SharePresenter: ShareInteractorOutput
{
}

class ShareConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ShareConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ShareViewController)
  {
    let router = ShareRouter()
    router.viewController = viewController
    
    let presenter = SharePresenter()
    presenter.output = viewController
    
    let interactor = ShareInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
