//
//  SharePresenter.swift
//  TheArabianCenter
//
//  Created by Ahmed Henawey on 2/23/17.
//  Copyright (c) 2017 Ahmed Henawey. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SharePresenterInput
{
    func presentShareSucceed(shareResponse:Share.Response)
    func presentShareError(error: Share.Error)
}

protocol SharePresenterOutput: class
{
    func displayShareSuccess(viewModel: Share.ViewModel)
    func displayMessage(title: String, message:String,actionTitle:String)
}

class SharePresenter: SharePresenterInput
{
  weak var output: SharePresenterOutput!
  
  // MARK: - Presentation logic
  
    func presentShareSucceed(shareResponse :Share.Response){
        // Format the response from the Interactor and pass the result back to the View Controller
        
    }
    func presentShareError(error: Share.Error){
        // Format the response from the Interactor and pass the result back to the View Controller
        
        switch error {
        default:
            self.output.displayMessage(title: NSLocalizedString("Canceled", comment: ""), message: NSLocalizedString("Can't claim until share the offer on social media", comment: ""), actionTitle: NSLocalizedString("Ok", comment: ""))
        }
    }
}
